import type { Metadata } from "next";

import {PropsWithChildren} from "react";
import Header from "@/components/features/layout/header/Header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function SiteLayout({
  children,
}: PropsWithChildren<unknown>) {
   return <div className="flex h-full flex-col">
       <div className="flex-1">
           <div className="fixed inset-y-0 z-50 h-[75px] w-full">
                <Header />
           </div>
           <main className="mt-[75px]">{children}</main></div>
   </div>
}
